//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beeper.Gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Beeper.Gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to do what you where doing and I didn&apos;t handle it properly, so here we are.
        ///
        ///If you let me, I can send an error report to my developers to help them figure out what went wrong, and fix it.
        ///
        ///What do you want to do?.
        /// </summary>
        internal static string CrashDialogContent {
            get {
                return ResourceManager.GetString("CrashDialogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the program.
        /// </summary>
        internal static string CrashDialogDontSend {
            get {
                return ResourceManager.GetString("CrashDialogDontSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something&apos;s gone horribly wrong!.
        /// </summary>
        internal static string CrashDialogInstruction {
            get {
                return ResourceManager.GetString("CrashDialogInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send an error report and close the program.
        /// </summary>
        internal static string CrashDialogSendReport {
            get {
                return ResourceManager.GetString("CrashDialogSendReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beeper has Crashed!.
        /// </summary>
        internal static string CrashDialogTitle {
            get {
                return ResourceManager.GetString("CrashDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t ask me again..
        /// </summary>
        internal static string DontAskMeAgain {
            get {
                return ResourceManager.GetString("DontAskMeAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} occurred!.
        /// </summary>
        internal static string ExceptionOccured {
            get {
                return ResourceManager.GetString("ExceptionOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t find the file needed to launch the Beeper CLI. You&apos;re going to have to find and run it yourself. Sorry!.
        /// </summary>
        internal static string GUICantFindCLI {
            get {
                return ResourceManager.GetString("GUICantFindCLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whoops!.
        /// </summary>
        internal static string GUICantFindCLIInstruction {
            get {
                return ResourceManager.GetString("GUICantFindCLIInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I couldn&apos;t find that!.
        /// </summary>
        internal static string GUICantFindCLITitle {
            get {
                return ResourceManager.GetString("GUICantFindCLITitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings reset successfully!.
        /// </summary>
        internal static string GUISettingsReset {
            get {
                return ResourceManager.GetString("GUISettingsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Reset!.
        /// </summary>
        internal static string GUISettingsResetTitle {
            get {
                return ResourceManager.GetString("GUISettingsResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! I need to write a configuration file to save some settings, but I can&apos;t because the folder I&apos;m currently in is write protected.
        ///Can I relaunch as administrator and try again?.
        /// </summary>
        internal static string GUIUnableToWriteConfig {
            get {
                return ResourceManager.GetString("GUIUnableToWriteConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write configuration file..
        /// </summary>
        internal static string GUIUnableToWriteConfigInstruction {
            get {
                return ResourceManager.GetString("GUIUnableToWriteConfigInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        internal static string GUIUnableToWriteConfigTitle {
            get {
                return ResourceManager.GetString("GUIUnableToWriteConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beeper Experimental GUI.
        /// </summary>
        internal static string GUIWarningInstruction {
            get {
                return ResourceManager.GetString("GUIWarningInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like you&apos;re trying to run the Beeper GUI. This shouldn&apos;t be an issue, but I have some problems I should probably warn you about.
        ///
        ///Currently, I&apos;m highly experimental and very messy. I doesn&apos;t work anywhere near properly, will almost definitely crash and probably destroy some of your data/hard work.
        ///
        ///I&apos;m also very likely to change in huge ways over the next few months with features being added, removed or just moved around.
        ///
        ///I recommend you continue to use the CLI until further notice.
        ///
        ///What  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GUIWarningMessage {
            get {
                return ResourceManager.GetString("GUIWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental GUI.
        /// </summary>
        internal static string GUIWarningTitle {
            get {
                return ResourceManager.GetString("GUIWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Stack Trace.
        /// </summary>
        internal static string HideStackTrace {
            get {
                return ResourceManager.GetString("HideStackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK, Relaunch as Administrator..
        /// </summary>
        internal static string RelaunchAsAdministrator {
            get {
                return ResourceManager.GetString("RelaunchAsAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK, Run the CLI..
        /// </summary>
        internal static string RunCLI {
            get {
                return ResourceManager.GetString("RunCLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t care! Proceed to the GUI!.
        /// </summary>
        internal static string RunGUI {
            get {
                return ResourceManager.GetString("RunGUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details.
        /// </summary>
        internal static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Stack Trace.
        /// </summary>
        internal static string ShowStackTrace {
            get {
                return ResourceManager.GetString("ShowStackTrace", resourceCulture);
            }
        }
    }
}
